name: Build and Upload Docker Image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-upload:
    name: "Build and Upload"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log into Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: prestonltaylor/jssrepl
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./JSSRepl/Presentation.Server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/jssrepl:latest
        labels: ${{ steps.metadata.outputs.labels }}
  publish:
    name: "Publish to VPS"
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
    - name: Execute docker-compose on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ${{ secrets.JSSREPL_COMPOSE_DIR }}
          docker compose pull
          docker compose down
          docker compose up -d